
version: "3.6"

x-substrate-adapter-def: &substrate-adapter-def
  image: ubinix5warun/dev:substrate-adapter-metadata-13.1
  restart: on-failure
  env_file:
    - ./adapter.env
  networks:
    - pp-substrate
#   depends_on:
#     - chain

services:
#   chain:
#     container_name: chain
#     image: ubinix5warun/chainlink-polkadot:latest
#     working_dir: /var/www/node-template
#     ports:
#       - "9944:9944"
#     environment:
#       - CARGO_HOME=/var/www/node-template/.cargo
#     volumes:
#       - "chain:/root/.local"
#     command: bash -c "/node-template --dev --ws-external"
#     networks:
#       - pp-substrate


  substrate-adapter1:
    <<: *substrate-adapter-def
    container_name: substrate-adapter1
    ports:
      - "8081:8080"
    environment:
      - "SA_PRIVATE_KEY=0x2875481aae0807cf598d6097c901a33b36241c761158c85852a6d79a8f20bc62"
    # Secret phrase `dry squeeze youth enjoy provide blouse claw engage host what horn next` is account:
    #  Secret seed:      0x2875481aae0807cf598d6097c901a33b36241c761158c85852a6d79a8f20bc62
    #  Public key (hex): 0x7c522c8273973e7bcf4a5dbfcc745dba4a3ab08c1e410167d7b1bdf9cb924f6c
    #  Account ID:       0x7c522c8273973e7bcf4a5dbfcc745dba4a3ab08c1e410167d7b1bdf9cb924f6c
    #  SS58 Address:     5EsiCstpHTxarfafS3tvG7WDwbrp9Bv6BbyRvpwt3fY8PCtN

  substrate-adapter2:
    <<: *substrate-adapter-def
    container_name: substrate-adapter2
    ports:
      - "8082:8080"
    environment:
      - "SA_PRIVATE_KEY=0x00ed255f936202d04c70c02737ba322a7aaf961e94bb22c3e15d4ec7f44ab407"
    # Secret phrase `price trip nominee recycle walk park borrow sausage crucial only wheel joke` is account:
    #  Secret seed:      0x00ed255f936202d04c70c02737ba322a7aaf961e94bb22c3e15d4ec7f44ab407
    #  Public key (hex): 0x06f0d58c43477508c0e5d5901342acf93a0208088816ff303996564a1d8c1c54
    #  Account ID:       0x06f0d58c43477508c0e5d5901342acf93a0208088816ff303996564a1d8c1c54
    #  SS58 Address:     5CDogos4Dy2tSCvShBHkeFeMscwx9Wi2vFRijjTRRFau3vkJ


networks:
  pp-substrate:
    name: pp-substrate